#!/usr/bin/env python3
"""Extract the granted-skill stat ids from the live trade2 stats table.

Wands, sceptres, spirit bases and many uniques carry a rolled
`Grants Skill: Level N <Name>` property. The level is a real search axis —
a Level 20 Chaos Bolt wand and a Level 12 one are different items to a
buyer — and it lives in its own **skill** group, one id per skill:

    skill.chaosbolt   "Grants Skill: Level # Chaos Bolt"

Usage:
    python3 scripts/resolve_skills.py stats.json > src/sox/data/skills.toml
"""

import json
import re
import sys

SKILL_GROUP = "skill"
GRANTS = re.compile(r"^Grants Skill: Level # (.+)$")


def normalize_name(text):
    """Fold case/whitespace so a re-cased skill still matches."""
    return re.sub(r"\s+", " ", text.casefold()).strip()


def main():
    stats = json.load(open(sys.argv[1]))

    # A few skill names carry two ids — one for the ordinary skill, one for a
    # unique's or a support's own copy (Lightning Bolt vs the Breach version).
    # The clipboard prints only the name, so prefer the id whose slug IS the
    # name; failing that, the shorter id, which is consistently the plain one.
    by_name = {}
    for group in stats["result"]:
        if group["id"] != SKILL_GROUP:
            continue
        for entry in group["entries"]:
            match = GRANTS.match(entry["text"])
            if not match:
                continue
            by_name.setdefault(normalize_name(match.group(1)), []).append(
                (match.group(1), entry["id"])
            )

    resolved, ambiguous = {}, []
    for key, options in by_name.items():
        if len(options) > 1:
            slug = key.replace(" ", "_").replace("'", "")
            exact = [o for o in options if o[1] == f"{SKILL_GROUP}.{slug}"]
            chosen = exact[0] if exact else min(options, key=lambda o: len(o[1]))
            ambiguous.append((chosen, options))
        else:
            chosen = options[0]
        resolved[chosen[0]] = chosen[1]

    out = [
        "# Granted skill -> trade2 stat id.",
        "# GENERATED by scripts/resolve_skills.py from the live stats table.",
        "#",
        "# A rolled `Grants Skill: Level N` is always searched, with N as the",
        "# minimum — it is the whole identity of a wand or sceptre, and a buyer",
        "# filtering for the skill will not accept a lower level of it.",
        "",
        "[skill]",
    ]
    for name in sorted(resolved):
        escaped = name.replace('"', '\\"')
        out.append(f'"{escaped}" = "{resolved[name]}"')

    print("\n".join(out))
    print(f"# {len(resolved)} skills resolved", file=sys.stderr)
    for chosen, options in ambiguous:
        others = ", ".join(i for _, i in options if i != chosen[1])
        print(f"#   ambiguous: {chosen[0]} -> {chosen[1]} (also {others})", file=sys.stderr)
    if not resolved:
        print("# ERROR: no granted skills found — has the group changed?", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
