#!/usr/bin/env python3
"""Resolve the crafting-base allowlist against the live trade2 item table.

Base value in PoE2 is driven mostly by item level and base class, not by a
curated "best base" list — so this file encodes the *rules* (ilvl breakpoints,
tracked slots, attribute-type mod access, Runeforged variants) and verifies the
handful of named meta bases that build guides call out by name.

Any named base that does not exist in the live table is reported loudly rather
than silently dropped.

Usage:
    curl -A '<ua>' https://www.pathofexile.com/api/trade2/data/items -o items.json
    python3 scripts/resolve_base_allowlist.py items.json > src/sox/data/base_allowlist.toml
"""

import json
import sys
from collections import OrderedDict

# Item level breakpoints. ilvl 82 is the widely cited endgame target because
# every Tier 1 modifier can roll there; 81 unlocks most; 80 is marginal.
# NB: some individual mods gate higher (85+ is cited for certain armour mods),
# so this is a graded score, not a promise that every mod is available.
ILVL_TIERS = [
    (82, 3, "all T1 mods can roll — the endgame crafting target"),
    (81, 2, "most T1 mods; +5 spell skill levels on wands gates here"),
    (80, 1, "marginal; only worth it on a strong base"),
]

# Slots worth spending a search on, with the defence axis that prices them.
# Category ids verified against /api/trade2/data/filters (type_filters.category).
TRACKED_SLOTS = [
    ("armour.chest", "ar,ev,es", 3, "highest defence budget; Deflection mods live here"),
    ("armour.helmet", "ar,ev,es", 2, "ES helmets are a known crafting-for-profit target"),
    ("armour.gloves", "ar,ev,es", 2, None),
    ("armour.boots", "ar,ev,es", 2, "movement speed gates value"),
    ("armour.shield", "ar,ev,es,block", 2, None),
    ("armour.focus", "es", 2, None),
    ("armour.quiver", None, 2, None),
    ("accessory.amulet", None, 3, "skill levels + spirit make these premium"),
    ("accessory.ring", None, 2, None),
    ("accessory.belt", None, 2, None),
    # Quarterstaves are "warstaff" in the trade taxonomy, not "quarterstaff".
    ("weapon.warstaff", "dps,pdps,crit,aps", 3, None),
    ("weapon.spear", "dps,pdps,crit,aps", 3, None),
    ("weapon.bow", "dps,pdps,crit,aps", 3, None),
    ("weapon.crossbow", "dps,pdps,crit,aps", 3, None),
    ("weapon.wand", "dps,edps,crit", 3, None),
    ("weapon.sceptre", "dps,crit", 2, "spirit implicit drives price"),
    ("weapon.staff", "dps,edps,crit", 2, None),
    ("weapon.twomace", "dps,pdps,crit", 2, None),
    ("jewel", None, 2, None),
]

# Bases named explicitly by 0.5 build guides. Weight 2 = priority within budget.
NAMED_BASES = [
    ("Sinister Quarterstaff", 2, "Martial Artist: base crit, unlike Dreaming"),
    ("Skullcrusher Quarterstaff", 2, "Whirling Assault Titan pick"),
    ("Winged Spear", 2, "attack-speed set for Whirling Slash"),
    ("Soaring Spear", 2, None),
    ("Akoyan Spear", 2, "Lightning Spear Amazon endgame base"),
    ("Seaglass Spear", 1, "progression base"),
    ("Spiked Spear", 1, "Ritualist bleed"),
    ("Omen Sceptre", 2, "Malice / crit chance implicit"),
    ("Primed Quiver", 2, "attack speed"),
    ("Pearlescent Amulet", 2, "+projectile skill levels target"),
    ("Absent Amulet", 2, "Eternal Rage implicit; enables Rage scaling"),
    ("Rattling Sceptre", 1, "Skeletal Warriors foundation for minion builds"),
    ("Ancestral Tiara", 2, "highest-ES helmet base"),
    ("Kamasan Tiara", 2, "budget ES helmet; sells near Ancestral on total ES"),
    ("Sorcerous Tiara", 1, None),
    ("Time-Lost Diamond", 2, "premium jewel base"),
]

# Bases guides explicitly warn against, so the scorer can avoid wasting budget.
AVOID_BASES = [
    ("Dreaming Quarterstaff", "higher base damage but 0% base crit — guides say skip"),
]

# Attribute type of an armour base gates which premium mods can roll on it.
ATTRIBUTE_RULES = [
    ("str", "#% of Armour also applies to Elemental Damage"),
    ("dex", "Gain Deflection Rating equal to #% of Evasion Rating"),
    ("int", "#% faster start of Energy Shield Recharge (body armour)"),
]

# 0.5 rune bases come in two families, and BOTH matter:
#   Runeforged   — 428 bases, the crafting-target variants
#   Runemastered — 218 bases, which carry 214 of the game's 464 uniques
RUNE_PREFIXES = ("Runeforged ", "Runemastered ")


def load_bases(items):
    """Base types only — entries carrying a `name` are uniques, not bases."""
    bases = set()
    for group in items["result"]:
        for entry in group["entries"]:
            if not entry.get("name"):
                bases.add(entry["type"])
    return bases


def main():
    items = json.load(open(sys.argv[1]))
    bases = load_bases(items)
    rune_counts = {
        prefix.strip(): len([b for b in bases if b.startswith(prefix)])
        for prefix in RUNE_PREFIXES
    }

    missing = []
    out = [
        "# Default crafting-base allowlist for sox.",
        "# GENERATED by scripts/resolve_base_allowlist.py — named bases verified",
        "# against the live trade2 item table. Do not hand-edit base names.",
        "",
        "# Item level is the primary axis of base value.",
    ]

    for ilvl, weight, note in ILVL_TIERS:
        out += ["[[ilvl_tier]]", f"min = {ilvl}", f"weight = {weight}", f'note = "{note}"', ""]

    out.append("# Slots worth spending a search on. Category ids verified against")
    out.append("# /api/trade2/data/filters (type_filters.category).")
    out.append("")
    for category, axes, weight, note in TRACKED_SLOTS:
        out += ["[[slot]]", f'category = "{category}"', f"weight = {weight}"]
        if axes:
            out.append(f'defence_axes = "{axes}"')
        if note:
            out.append(f'note = "{note}"')
        out.append("")

    out.append("# Bases named outright by 0.5 build guides.")
    out.append("")
    for name, weight, note in NAMED_BASES:
        if name not in bases:
            missing.append(name)
            continue
        out += ["[[named_base]]", f'name = "{name}"', f"weight = {weight}"]
        if note:
            out.append(f'note = "{note}"')
        out.append("")

    for name, note in AVOID_BASES:
        if name not in bases:
            missing.append(name)
            continue
        out += ["[[avoid_base]]", f'name = "{name}"', f'note = "{note}"', ""]

    out.append("# 0.5 rune bases are distinct items from their plain twins.")
    out.append("# Runemastered bases are what most uniques are built on.")
    out.append("")
    for prefix, count in rune_counts.items():
        out += [
            "[[rune_family]]",
            f'prefix = "{prefix}"',
            "bonus_weight = 2",
            f"count = {count}",
            "",
        ]

    out.append("# Attribute type of an armour base gates its premium mods.")
    out.append("")
    for attr, mod in ATTRIBUTE_RULES:
        out += ["[[attribute_rule]]", f'attribute = "{attr}"', f'unlocks = "{mod}"', ""]

    print("\n".join(out))

    print(
        f"# {len(bases)} bases in table ({rune_counts}); "
        f"{len(NAMED_BASES) + len(AVOID_BASES) - len(missing)}"
        f"/{len(NAMED_BASES) + len(AVOID_BASES)} named bases verified",
        file=sys.stderr,
    )
    if missing:
        print("# UNRESOLVED (not present in the live item table):", file=sys.stderr)
        for name in missing:
            print(f"#   {name}", file=sys.stderr)


if __name__ == "__main__":
    main()
