#!/usr/bin/env python3
"""Extract the stat ids of mods that carry NO number.

A mod with a roll is searched at that roll — "+31 to Dexterity" becomes
`# to Dexterity` with a minimum of 31. A mod without one has nothing to
compare, so the whole query builder skipped it, and an item whose identity is
a flag went to market described only by its category.

Mastered Domain is that item. The Irradiated Tablet comes in six biomes and
the biome is the entire good:

    Map also counts as a Forest Map     55 ex   (8,620 listed)
    Map also counts as a Desert Map      1 ex

Nothing in the query said Forest, so the search returned every biome sorted
by price and the cheapest one — a Desert at 1 exalted — set the price of a
55 exalted tablet. The index is no better: it reports one number for all
26,357 of them.

Value-less mods are the easy half of the stats table to resolve. There is no
roll to placeholder, so the item's wording and the table's text are the same
string, and an exact match is not a guess. A text that appears twice in one
group IS a guess, so it is dropped.

Usage:
    curl -A '<ua>' https://www.pathofexile.com/api/trade2/data/stats -o stats.json
    python3 scripts/resolve_flag_mods.py stats.json > src/sox/data/flag_mods.toml
"""

import collections
import json
import sys

# Where a rolled mod and a flag mod differ: only these two groups hold mods an
# item carries as its own text. Enchant, rune and desecrated entries are
# reached through the allowlist's own group handling.
GROUPS = ("explicit", "implicit")


def flags(payload: dict, group_id: str) -> dict[str, str]:
    """Text -> stat id for every entry in `group_id` with no placeholder."""
    by_text: dict[str, list[str]] = collections.defaultdict(list)
    for group in payload["result"]:
        if group.get("id") != group_id:
            continue
        for entry in group.get("entries") or []:
            text, stat_id = entry.get("text"), entry.get("id")
            if not text or not stat_id or "#" in text:
                continue
            by_text[" ".join(text.split())].append(stat_id)

    # Two ids under one wording cannot be told apart from the item's text, and
    # sending the wrong one silently searches for something else.
    return {text: ids[0] for text, ids in sorted(by_text.items()) if len(ids) == 1}


def main(path: str) -> int:
    with open(path, encoding="utf-8") as fh:
        payload = json.load(fh)

    print("# Value-less mod text -> trade2 stat id.")
    print("# GENERATED by scripts/resolve_flag_mods.py from the live stats table.")
    print("#")
    print("# A mod with no number cannot be searched at a minimum, so the query")
    print("# builder dropped it and priced the item on its category alone. These")
    print("# are the ids that let a flag be searched as itself: the biome on a")
    print("# Mastered Domain tablet, the ground a map is covered in.")
    for group_id in GROUPS:
        resolved = flags(payload, group_id)
        print()
        print(f"[{group_id}]")
        for text, stat_id in resolved.items():
            print(f'"{text}" = "{stat_id}"')
        print(f"# {len(resolved)} entries", file=sys.stderr)
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        raise SystemExit(2)
    raise SystemExit(main(sys.argv[1]))
