#!/usr/bin/env python3
"""Extract every item base name from the live trade2 item table.

A normal, magic or unique item is bought as a BASE. The clipboard names it,
but not always cleanly: a magic item wraps its base in affixes, and a normal
one with quality prefixes "Superior".

    Crackling Temple Maul of the Brute   ->  Temple Maul
    Superior Divine Crown                ->  Divine Crown
    Heavy Belt                           ->  Heavy Belt

Without the base pinned, a search asks the market for a CATEGORY. Measured
live on an ilvl 81 Heavy Belt: 5,595 belts matched and the cheapest were a
Double Belt, a Mail Belt and a Wide Belt at 1 exalted apiece, none of them
the item in hand. Pinned to Heavy Belt the same search matched 4,896 and the
cheapest was 14 exalted, which is what the belt is worth.

Usage:
    curl -A '<ua>' https://www.pathofexile.com/api/trade2/data/items -o items.json
    python3 scripts/resolve_bases.py items.json > src/sox/data/item_bases.toml
"""

import json
import sys


def bases(payload: dict) -> list[str]:
    """Every distinct `type`, over every group.

    Unique entries carry a name AND the base they are found on, and that base
    is wanted too: it is what a unique's own search pins beside its name.
    """
    found = set()
    for group in payload["result"]:
        for entry in group.get("entries") or []:
            base = entry.get("type")
            if base:
                found.add(" ".join(base.split()))
    return sorted(found)


def main(path: str) -> int:
    with open(path, encoding="utf-8") as fh:
        payload = json.load(fh)

    resolved = bases(payload)
    if not resolved:
        print("# ERROR: no bases found — has the table changed?", file=sys.stderr)
        return 1

    print("# Item base names.")
    print("# GENERATED by scripts/resolve_bases.py from the live item table.")
    print("#")
    print("# Used to pin the base of a normal, magic or unique item, which the")
    print("# clipboard does not always give cleanly: a magic item wraps its base")
    print("# in affixes, and a normal one with quality prefixes \"Superior\".")
    print()
    print("types = [")
    for base in resolved:
        escaped = base.replace('"', '\\"')
        print(f'  "{escaped}",')
    print("]")
    print(f"# {len(resolved)} bases resolved", file=sys.stderr)
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        raise SystemExit(2)
    raise SystemExit(main(sys.argv[1]))
