#!/usr/bin/env python3
"""Extract the granted-skill stat ids from the live trade2 stats table.

Wands, sceptres, spirit bases and many uniques carry a rolled
`Grants Skill: Level N <Name>` property. The level is a real search axis —
a Level 20 Chaos Bolt wand and a Level 12 one are different items to a
buyer — and it lives in its own **skill** group, one id per skill:

    skill.chaosbolt   "Grants Skill: Level # Chaos Bolt"

Usage:
    python3 scripts/resolve_skills.py stats.json > src/sox/data/skills.toml
"""

import json
import re
import sys

SKILL_GROUP = "skill"
GRANTS = re.compile(r"^Grants Skill: Level # (.+)$")


def normalize_name(text):
    """Fold case/whitespace so a re-cased skill still matches."""
    return re.sub(r"\s+", " ", text.casefold()).strip()


def main():
    stats = json.load(open(sys.argv[1]))

    # Three skill names carry two ids — one for the ordinary skill, one for a
    # triggered or reserved copy: Decompose is skill.corpse_cloud and
    # skill.corpse_cloud_triggered, and Lightning Bolt and Blink are the same
    # shape. The clipboard prints only "Grants Skill: Level 18 Decompose", so
    # nothing in the item says which, and picking the shorter id picked wrong:
    # Corpsewade Iron Greaves grants the TRIGGERED one, so a search for
    # skill.corpse_cloud returned 0 listings of the 1,806 that exist and the
    # boots came back as having no comparable listing at all.
    #
    # Every id is kept and the query asks for at least one of them. A skill
    # name matching two ids is a fact about GGG's table, not a decision this
    # script gets to make.
    by_name = {}
    for group in stats["result"]:
        if group["id"] != SKILL_GROUP:
            continue
        for entry in group["entries"]:
            match = GRANTS.match(entry["text"])
            if not match:
                continue
            by_name.setdefault(normalize_name(match.group(1)), []).append(
                (match.group(1), entry["id"])
            )

    resolved, ambiguous = {}, []
    for _key, options in by_name.items():
        name = options[0][0]
        ids = sorted({stat_id for _name, stat_id in options})
        resolved[name] = ids
        if len(ids) > 1:
            ambiguous.append((name, ids))

    out = [
        "# Granted skill -> trade2 stat id.",
        "# GENERATED by scripts/resolve_skills.py from the live stats table.",
        "#",
        "# A rolled `Grants Skill: Level N` is always searched, with N as the",
        "# minimum — it is the whole identity of a wand or sceptre, and a buyer",
        "# filtering for the skill will not accept a lower level of it.",
        "#",
        "# A list, because a skill name can carry two ids — the plain skill and",
        "# a triggered or reserved copy of it — and the item text says only the",
        "# name. Both are searched as \"at least one of these\".",
        "",
        "[skill]",
    ]
    for name in sorted(resolved):
        escaped = name.replace('"', '\\"')
        ids = ", ".join(f'"{stat_id}"' for stat_id in resolved[name])
        out.append(f'"{escaped}" = [{ids}]')

    print("\n".join(out))
    print(f"# {len(resolved)} skills resolved", file=sys.stderr)
    for name, ids in ambiguous:
        print(f"#   two ids, both searched: {name} -> {', '.join(ids)}", file=sys.stderr)
    if not resolved:
        print("# ERROR: no granted skills found — has the group changed?", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
