#!/usr/bin/env python3
"""Extract the notable-allocation stat ids from the live trade2 stats table.

Notable-granting jewels (Megalomaniac, the Time-Lost family) are priced
entirely by WHICH notables they allocate. The index cannot express that — it
reports one number for every Megalomaniac, currently 1 exalted across ~25,000
listings — so these must be priced by search, and the search needs the exact
stat id per notable.

Notables live in the **enchant** group, not explicit. Verified against the
live search API: `explicit.stat_2954116742|50562` returns 0 results while
`enchant.stat_2954116742|50562` returns 11. The same numeric id appears under
several groups, and only the enchant one matches listed jewels.

    enchant.stat_2954116742|50562   "Allocates Barbaric Strength"

Usage:
    python3 scripts/resolve_notables.py stats.json > src/sox/data/notables.toml
"""

import json
import re
import sys

PREFIX = "Allocates "

# Notables match only under the enchant group; explicit/crafted return nothing.
NOTABLE_GROUP = "enchant"


def normalize_name(text):
    """Fold case/whitespace so a re-cased notable still matches."""
    return re.sub(r"\s+", " ", text.casefold()).strip()


def main():
    stats = json.load(open(sys.argv[1]))

    notables = {}
    for group in stats["result"]:
        if group["id"] != NOTABLE_GROUP:
            continue
        for entry in group["entries"]:
            text = entry["text"]
            if not text.startswith(PREFIX):
                continue
            # "Allocates # Sinister Jewel sockets" is a socket count, not a
            # notable, and has no per-notable id.
            if "|" not in entry["id"]:
                continue
            notables[text[len(PREFIX):]] = entry["id"]

    out = [
        "# Notable -> trade2 stat id.",
        "# GENERATED by scripts/resolve_notables.py from the live stats table.",
        "#",
        "# Used to price notable-granting jewels (Megalomaniac, Time-Lost). The",
        "# index reports one price for all of them regardless of which notables",
        "# they carry, so these are always priced by search instead.",
        "",
        "[notable]",
    ]
    for name in sorted(notables):
        escaped = name.replace('"', '\\"')
        out.append(f'"{escaped}" = "{notables[name]}"')

    print("\n".join(out))
    print(f"# {len(notables)} notables resolved", file=sys.stderr)
    if not notables:
        print("# ERROR: no notables found — has the stat id scheme changed?", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
